[package]
name = "rustGOL"
version = "0.1.0"
authors = ["thrombe <yash.n.thombare620@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ncurses = "5.101.0"
serde_json = "1.0.59"
# serde = "1.0.126"
